apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: autoscalers.dusdjhyeon.com
spec:
  group: dusdjhyeon.com
  names:
    kind: AutoScaler
    listKind: AutoScalerList
    plural: autoscalers
    singular: autoscaler
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                upperBound:
                  type: integer
                scaleTargetRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
