apiVersion: batch/v1
kind: CronJob
metadata:
  name: cpu-scaling-operator-cronjob
  namespace: default
spec:
  schedule: "0 2 * * *"  # every 2AM
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cpu-scaling-operator
            image: dusdjhyeon/cpu-scaling-operator:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure
