apiVersion: v1
kind: namespace
metadata:
  labels:
    control-plane: controller-manager
  name: operators
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: operators 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gp-operator
  template:
    metadata:
      labels:
        app: gp-operator
    spec:
      serviceAccountName: controller-manager
      containers:
      - name: gp-operator
        image: dusdjhyeon/gp-operator:latest
        imagePullPolicy: Always
