apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: adas-urban
spec:
  forProvider:
    location: us-central1-a
    autopilot:
      enabled: true
    nodeConfig:
      preemptible: true
  writeConnectionSecretToRef:
    name: auto-kube
    namespace: default